server.port: 8080

spring:
  application:
    name: my-market-app
  datasource:
    url: jdbc:h2:file:${project.dir:.}/db/data;MODE=PostgreSQL;DEFAULT_NULL_ORDERING=HIGH
    driverClassName: org.h2.Driver
    username: admin
    password: admin